name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.madsba.dk
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            registry.madsba.dk/ts3-online:latest
